sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: AyMehakVl0hghEZ9E1UDcEQYUHruNpUDdJNzR/Q9qjFL6YaXa/W8gsDDiaQT9zQS4yyBAdN8HU9Wbfmo1CUGJNRmgHprEJ4fgavMZyL+iszOJS8ZQfhPRlBmwWcna0XjbqasjKP/JxYyrRUG2c/eSRzP6AwZlktCYomH1qE86NMUCXlHryACQ9I8TBcPeWRrYcln9pw83VKJ+Cj5Tm/53ciq852wdsO1ehlfMtGNKK3wiKUs2BHh41Mwp0r6FIcFASCEBbpTqioZDTw0CDfLdqRf5b+jORKz8OlQ7GEtGXeLJYf7BoqVKFhXwsyk6wfVgx6lzPqGDdhf+JpTDYIOSd3eQ6NNx86c+N1Ay2SAmaCB1ejNDNF9X5DeKExoovUOzJd2sBpvB9LzGJBiqY1TARKJnk95fZNXPZT9tcLXOyF1Szf5MWoyVE7301DdP1oWA7UuCUhF5/vSBMCT35Oj4SqF02VTwj7xzTAe3ybqaY33gJ1BmmAKB3sVGMpp7nnXriiV1OHG3jgyqJQ86mDP12octAMrfGpLxTd4FngnuRmcNOLcVy/72TBHbw/X4cobs5UwBA+NpcrJ9gAUTarRqokM/mLKGeRsAyxwpA6EH0KoV+sLZ0C1zF4oN2IM3wTDi8e+SHurWHS6kljTvDC6YLKZ63DPBiRANni+VMcgZNg=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Sisters-Volume-3_5463
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy